services:
  - type: worker
    name: slate-bot
    env: python
    plan: standard
    branch: main
    repo: https://github.com/ggonavy/slate-bot
    buildCommand: pip install --no-cache-dir setuptools==70.3.0 && pip install --no-cache-dir -r requirements.txt
    startCommand: python Slate_PythonBot_v12_Strategy.py
    rootDir: src
    region: us-east
    envVars:
      - key: KRAKEN_API_KEY
        sync: false
      - key: KRAKEN_API_SECRET
        sync: false
      - key: KRAKEN_API_KEY_HEDGE
        sync: false
      - key: KRAKEN_API_SECRET_HEDGE
        sync: false
    autoDeploy: false
