services:
  - type: worker
    name: Python_Bot
    env: python
    plan: standard
    buildCommand: pip install -r requirements.txt
    startCommand: python CoinbaseBot.py
    repo: https://github.com/ggonavy/Python_Bot
    runtime: python-3.10.12
