ssing fields):
yaml



services:
  - type: web
    name: slate-bot
    env: python
    plan: standard
    branch: main
    repo: https://github.com/ggonavy/slate-bot
    buildCommand: pip install -r requirements.txt
    startCommand: python Slate_PythonBot_v12_Strategy.py
    envVars:
      - key: KRAKEN_API_KEY
        sync: false
      - key: KRAKEN_API_SECRET
        sync: false
      - key: PORT
        value: 8080
    autoDeploy: false
